linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - golint
    - gosec
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  funlen:
    lines: 90
    statements: 50
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  golint:
    min-confidence: 0.6
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint