language: go
go:
  - "1.15"

services:
  - docker

env:
  global:
    # Github token
    - secure: w0bpFel/bPQDEVHqUZc1ABh3NFuVP1xL+CpGzmDftK0S8H6hj7RqikYbRgNglDQNcXnYJbT7HFnvoizJCig3xydHCUCeoLVPXJ63qRE8LrpfYovntmFJXkME8DEjM2S5t8Ur0A2IVCY+AFRVCjgrUf+M1aYq8AO57egtIc4WwYkWI9JXnqKfAQjRm470CV/u8L5QMVHUz+FsSrt9AD4p14+yWi1T3GwSTxtCyhzNCJ8RaDf9ciowZWNXSPhGoqeT21/zS+b9wIHfYsQoaoJg22i8f0AnkDKMOp7vfU4wWQvser8JaGLbyKwdCTrHZ2uc8PlttVwLLbkcl3O8f4QemNbN9BabF7ToigO9mrYlFO3gX6RaHbmhzSKftNSe86K5YxqzWLpd7zmd9c4dmIgm1KNEryYuQ10yMbJFw5Bdc3dEfeThznrcHvlIVds6aLbvobfVQbcfrNxr9zY/PWf0MJxWokBB2CVFtaUarfu+XjPnO9uuv1NMN5isO2DUhwNnRT8i2KddgCNS/IQv42aUnMklQ+/t+vtm1FJaXuLoEYgiII14m2TSKhRRzkDSKPzwL1Orrbv+WY7yI+P7KTJxP9TX8jT7chJIaE7gW0XJSe2fUp8b24vgHOlQzMxkl3ZZbCs96PI/b2FwXL9nGRkjJQz10SX+mbXVfGy6JmTcIBI=
    # Docker password
    - secure: odKWUB71bOOeANuNwXciaSJg8LZRPfjLK3XODY6f25KgjPPbDfaisL5doEGbKkznwmNk41gT6TMgkeGkKH2U3Sjc+IsslyFTVSu3Hv/1WJwEqGxUOEN7dX+0wYsyX5/RNzAaMMON2IjSssPEB820J2cTWN2ybGLAMhZRzAzJ75ZB+EUcnJ3zcHSWZc/o249a0gfl0ALQb2gmRaVBxM7S9JcMBFVNVvKiNbaAYl1okLXayoEzmVWbZg+zlYgMHj/1OQxAqUqYRSLtXwZdVVfLOmgrr+gcjVKN1AhROt9JP3MlGhDrS4yBKpUAXamZsbPHlCHIC5Rjvryh/NL6F03b78MI0t84FWTopxcpp3BEEUwN5eq1wQ6EdBsghzfO0489RjJF6YzI20gfJ9aiN7eR9nDQJO7I93cgvag8hyinR3UwCDafsKY4IfQMOiOk1b4rhMSIym5/fga6PHcpydadiM466hOyNde8OP5XKEK5J83HTHADYi1rH2yw8fENsFtOuLL13bIdPeN2+gzg4tYZSs+jTNjAtFkGQpVj2mvHaXTlaMwYl7aqz73cpn6WuGJR7PjAzzZlWY3Ichwmrs5javGxV6T5zfpmoPk020AUU70GhH0ANMipgjgtfez/Qbv/Wy5hFS4pUvY6d9yVyXBr2D+fBC0GpxFv2CV0aV/f7iM=
stages:
  - test
  - name: release
    if: (tag =~ ^v)

before_script:
  - make vendor

jobs:
  include:
    - stage: test
      name: "coverage"
      script: make coverage

    - stage: test
      name: "lint"
      script: make lint

    - stage: test
      name: "goreleaser check"
      script: curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

    - stage: release
      name: "Release"
      before_install:
        - test -n "$TRAVIS_TAG" && docker login -u=thomaspoignant -p="$DOCKER_PASSWORD"
      deploy:
        - provider: script
          cleanup: false
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux